language: node_js
node_js:
- node
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: pages
  local-dir: dist
  on:
    branch: master
  github-token:
    secure: QhziClEWRipfqICnZe9jHVg5T2PpqGZ5vdj1IaDLa2Slwrw9zlU0+WHraazoQKxm8TNRQHE0hcSznhm8tBhBH0u7RdFyzycTzYTqZ2VGyQ7LWRekisaCrLfrZS5+JQcwCEzy0fzYipfvv+aTRAc8FWkojjVhjfNNDDgjCYoS6eQDGY4b4PWwVZ+Goy1TVBEAKumSmgvFeatt6dXQBkADx/1D07/1eUM8Ai2kMefh3Uc78p9CMRfSa1V0mhX/RgCrHtom9ua1QvcmUky0b56QDTS7a2J3Unb6mN8QrLfqmFC31yIvIP8dfER0HO6jcdFkQ2RrVuYzJ0iEm+Jm99BZcEKcrSsehnHP/wlqhgKfYTTavHuKqHAiSDjfKIn7m5YvJW0MZI7vglgX6PaiFFg0VgezxLCBeiNBeXy/i+PiZ7s/Mm0MgpfOkYUkJtB4IgHMEu3h9O1OpQ818OVPNBuDJTa67+Vv6WffOMNhpKSLK4UHbACaxr3+UrUXDo6DYLYe9dSQGLwQBiQf7uaXVWk1PtBGFOcX1nfZRgRiOwLogINxCJ4iXJFj5rKSmtvhKHrpYftJ/L5Ai+iIkvPfyKSGqWjsvGOsI2IO5p7u4GXILlJeCcoafxlyY33SmEWE+rkS6EO1O631LthYhsedXg3HOxOkHP0rnKz6Na+LNra+Vkw=
