language: node_js
node_js:
  - node
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: pages
  local-dir: dist
env:
  global:
    secure: HsKzDskED+slo14P2L8cyL1zw2m41m2PU1ASrF6ZoNPCy0//orkDAdyRXfvW6Ck4bTSFFLBqzxa/afhB1hGcm2uOXOZi7zQbecx6n5K/LVLEGhfFOtrW7b+JOOoPZWHQg/EcI6IVEHRL+9a5Fy9CWm8L55qA8ADNk8kVDV7VwCq/UVAUyj/1elKe7I8b3KvLN5mCneSF5lsEytxIn3/6SKPK4/XOzydXayxdluVny/58jVXYK8GTOS3+jMFhE1HvCPybyup4bEgAd2poWYmwlAmI0Cz3t7RonBLR8OAolf9rpC/R+TNPsBfYTTXKHOh1utQeTdSm6BD9+VpfMnckSEyiIzoCVNrGfEYA47OiDOwLsR9hmQ0z+ZwLUg9jNzEu7U4gIwKANBVu7AgdsrSMncBDQDWfLqO4WQizQyEteJjbVP9H4DQ/zXiIy5WgcolkIqU2wZnhlKu1kNQE4ysf42ktDb0bwA7hNFmBuWe8VOtHp0wHh9l3n3EO3N6NNQJTJNl0GmGVpc2M3q8bvXktbqV+iacIBPMt3p46M/h1BFIZgb7JUREhVEJEOItjhDa4NrZvzWeQZXcLpHm6QD3cjzibfY7FVmekgqOyVlBXUoHiRBGpC9FUaD/3S9yaVxkX5+rv0ywwahmrhAZarQ6sjWLNstOFD2V8KmZ7LiPox5Y=
