language: node_js
node_js:
- node

script:
- npm run build

deploy:
  skip_cleanup: true
  provider: pages
  local-dir: dist
  github-token:
    secure: "UJwWzAq1MabmWKc4cTzQAf1AwRgcYllgnC2I9ex/iYUNAyf9jUmz81FvcLneGBjAO885Namu8O3RE57wHrj1uul2lhFFXM15ALp3I4rrMtEfW7cTMhmsqxpLKO6sqTjw6JI+uUUN/Tc8inHV7YuQxvCidnmzL5D2ENytrqrFpeIwCMta3UKZ2uMK0+KrMgd9JG9NmKvYGRGH1lpmK7Yq7gJtPJB/t/ACgsVcrAbhmMbh3ssaOidjPMc9aslqCepff8fIrMgacdficJ1b2NWOzjs1caQpHRpo4wassB+NJ8DNOkBikGNMUiD87TEdFZifj5MW8pU2j/sJv+ntLRAValDxw8DclYSE/Nt3PXD+AZwLFjkFM/VqMHLErGdEaS1YGVRoFIDm16J+AegoGyE6207hwh3ClyMI/bXy/HaPivppVqmkap2RMZlQoZ9MpOqbLtQtqz+nGRKqB+CM3Ngyj24/XxRZGBACq76wN4ncBnVxq2+RhclyZnd8HT5LGUsZ+q5M2msA7HawBOeYVshD98mDHf4DLnT1m7tarsM8aV2h6MEK4GiBq5y+/GQN84CER3XJMJLaczYDr0j5DJOIcM/MgPPJRbHeDxb4LB3iYmtTvyJo4wOIQAySPy30nMzady3BLkNga7zd5IpjxytyC1OLoXaZIgxaWFjgO6yPCls="
